os: windows
language: shell
script:
  - whoami.exe
  - ./make_Help_CD.bat
  - ./make_keyEvents_CD.bat
  - ./make_DelayAndEvent_CD.bat
  - ./make_BubbleSort_CD.bat
  - ./make_main_CD.bat
  - ls -al
  - powershell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
  - powershell ./windows.ps1
deploy:
  provider: releases
  skip_cleanup: true
  token: $GH_TOKEN
  file_glob: true
  file:
    - Sorting.Algorithm.Visualizor.exe
    - certificate.crt 
    - certificate.bat
  on:
    tags: true