os: windows
language: shell
script:
  - whoami.exe
  - ./CICD/make_Help_CICD.bat
  - ./CICD/make_ShowCode_CICD.bat
  - ./CICD/make_keyEvents_CICD.bat
  - ./CICD/make_DelayAndEvent_CICD.bat
  - ./CICD/make_BubbleSort_CICD.bat
  - ./CICD/make_InsertionSort_CICD.bat
  - ./CICD/make_main_CICD.bat
  - ls -al
  - powershell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
  - powershell ./CICD/windows.ps1
deploy:
  provider: releases
  skip_cleanup: true
  token: $GH_TOKEN
  file_glob: true
  file:
    - Sorting.Algorithm.Visualizor.exe
    - certificate.crt
  on:
    tags: true