os: windows
language: shell
script:
  - ./make_Help_CD.bat
  - ./make_keyEvents_CD.bat
  - ./make_DelayAndEvent_CD.bat
  - ./make_BubbleSort_CD.bat
  - ./make_main_CD.bat
deploy:
  provider: releases
  skip_cleanup: true
  token: $GH_TOKEN
  file_glob: true
  file:
    - "Main.exe"
  on:
    tags: true