os: windows
language: shell
script:
  - whoami.exe
  - ./make_Help_CD.bat
  - ./make_keyEvents_CD.bat
  - ./make_DelayAndEvent_CD.bat
  - ./make_BubbleSort_CD.bat
  - ./make_main_CD.bat
  - ls -al
  - powershell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
  - powershell -Command '& "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\signtool.exe" sign -a -fd SHA256 -t http://timestamp.comodoca.com/authenticode -f certificate.pfx Sorting.Algorithm.Visualizor.exe'
deploy:
  provider: releases
  skip_cleanup: true
  token: $GH_TOKEN
  file_glob: true
  file:
    - Sorting.Algorithm.Visualizor.exe
  on:
    tags: true